import { Resend } from "resend"
import { ApiError } from "../utils/ApiError.js"

const sendEmail = async (recipientEmail, summary) => {
    if (!process.env.RESEND_API_KEY) {
        throw new ApiError(500, "Resend API key not configured")
    }

    const resend = new Resend(process.env.RESEND_API_KEY)

    const { data, error } = await resend.emails.send({
        from: "onboarding@resend.dev",
        to: recipientEmail,
        subject: "Your Sales Report — Rabbitt AI",
        html: `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px;">
                
                <div style="background: #0f172a; padding: 20px; border-radius: 8px 8px 0 0;">
                    <h1 style="color: #ffffff; margin: 0; font-size: 22px;">
                        Rabbitt AI — Sales Insight Report
                    </h1>
                </div>

                <div style="background: #f8fafc; padding: 24px; border: 1px solid #e2e8f0; border-radius: 0 0 8px 8px;">
                    <p style="color: #475569; font-size: 14px; margin-top: 0;">
                        Here is your AI-generated summary based on the uploaded sales data.
                    </p>

                    <div style="background: #ffffff; border-left: 4px solid #6366f1; padding: 16px; border-radius: 4px;">
                        <p style="color: #1e293b; font-size: 15px; line-height: 1.7; white-space: pre-wrap;">
                            ${summary}
                        </p>
                    </div>

                    <p style="color: #94a3b8; font-size: 12px; margin-bottom: 0; margin-top: 20px;">
                        Generated by Deepanshu
                    </p>
                </div>

            </div>
        `,
    })

    if (error) {
        throw new ApiError(500, `Email sending failed: ${error.message}`)
    }

    return data
}

export { sendEmail }