import { Resend } from "resend"
import { ApiError } from "../utils/ApiError.js"

const formatEmailContent = (text) => {
    return text
        .split("\n")
        .filter((line) => line.trim() !== "")
        .map((line) => {
            const formatted = line
                .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
                .replace(/\*(.*?)\*/g, "<em>$1</em>")
            return `<p style="margin: 0 0 10px 0; color: #1e293b; font-size: 14px; line-height: 1.7;">${formatted}</p>`
        })
        .join("")
}

const sendEmail = async (recipientEmail, summary) => {
    if (!process.env.RESEND_API_KEY) {
        throw new ApiError(500, "Resend API key not configured")
    }

    const resend = new Resend(process.env.RESEND_API_KEY)

    const { data, error } = await resend.emails.send({
        from: "onboarding@resend.dev",
        to: recipientEmail,
        subject: "Your Sales Insight Report — Rabbitt AI",
        html: `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px;">
                
                <div style="background: #0f172a; padding: 20px; border-radius: 8px 8px 0 0;">
                    <h1 style="color: #ffffff; margin: 0; font-size: 20px; font-weight: 500;">
                        Rabbitt AI — Sales Insight Report
                    </h1>
                </div>

                <div style="background: #f8fafc; padding: 24px; border: 1px solid #e2e8f0; border-radius: 0 0 8px 8px;">
                    <p style="color: #64748b; font-size: 13px; margin: 0 0 20px 0;">
                        Here is your AI-generated summary based on the uploaded sales data.
                    </p>

                    <div style="background: #ffffff; border-left: 3px solid #2563eb; padding: 16px 20px; border-radius: 4px;">
                        ${formatEmailContent(summary)}
                    </div>

                    <p style="color: #94a3b8; font-size: 11px; margin: 20px 0 0 0;">
                        Generated by Rabbitt AI
                    </p>
                </div>

            </div>
        `,
    })

    if (error) {
        throw new ApiError(500, `Email sending failed: ${error.message}`)
    }

    return data
}

export { sendEmail }